;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	TeX-insert-backslash
	beginning-of-visual-line
	end-of-visual-line
	org-beginning-of-line
	org-delete-char
	))

(setq mc/cmds-to-run-once
      '(
	org-self-insert-command
	))
